"""Fixed typo in description field

Revision ID: 57e89218ed58
Revises: 
Create Date: 2025-03-04 23:21:53.376306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e89218ed58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.drop_column('decription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decription', sa.TEXT(), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
